network:
  ethernets:
    enp0s3:
      dhcp4: true
    enp0s8:
      dhcp4: false
      addresses: [ipmaquina/24]
      gateway4: defgate
      nameservers:
       addresses: [defgate]
  version: 2 